/// Generated by AssetsRefGenerator on 2022/07/21
class Res {
  static const String appicon = "assets/images/appicon.png";
  static const String asste = "assets/images/asste.png";
  static const String blueSimple = "assets/json/blueSimple.json";
  static const String forward_icon = "assets/svg/forward_icon.svg";
  static const String list = "assets/images/list.png";
  static const String main_logo = "assets/png/main_logo.png";
  static const String skip_icon = "assets/svg/skip_icon.svg";
  static const String star_icon = "assets/svg/star_icon.svg";
  static const String thumbnail = "assets/png/thumbnail.png";
  static const String user_icon = "assets/svg/user_icon.svg";
}
